// All tools available per Axiom Packer provisioner image (Go + non-Go combined).
// Shared source of truth for provisioner/AMI-aware module filtering —
// used by ScanLauncher (single scans) and WorkflowBuilder (chained workflows).
export const PROVISIONER_TOOLS: Record<string, string[]> = {
  barebones: [
    "anew",
    "cero",
    "commix",
    "corsy",
    "dnsx",
    "dnsgen",
    "dnsrecon",
    "exec",
    "gorgo",
    "gowitness",
    "httpx",
    "ipcdn",
    "linkfinder",
    "masscan",
    "nmap",
    "nuclei",
    "openredirex",
    "paramspider",
    "subfinder",
    "trufflehog",
  ],
  default: [
    "amass",
    "anew",
    "aquatone",
    "arjun",
    "assetfinder",
    "cero",
    "chaos-client",
    "commix",
    "crlfuzz",
    "dalfox",
    "dirdar",
    "dirsearch",
    "dnscewl",
    "dnsx",
    "dnsvalidator",
    "feroxbuster",
    "ffuf",
    "gau",
    "gauplus",
    "gobuster",
    "gospider",
    "gowitness",
    "gxss",
    "hakrawler",
    "hakrevdns",
    "httprobe",
    "httpx",
    "interactsh-client",
    "ipcdn",
    "jaeles",
    "katana",
    "kiterunner",
    "kxss",
    "masscan",
    "massdns",
    "meg",
    "naabu",
    "nmap",
    "nuclei",
    "puredns",
    "rustscan",
    "s3scanner",
    "scrying",
    "shuffledns",
    "sqlmap",
    "subfinder",
    "subjs",
    "testssl",
    "tlsx",
    "trufflehog",
    "unimap",
    "wafw00f",
    "waybackurls",
    "webscreenshot",
    "whois",
    "wpscan",
  ],
  reconftw: [
    "asm",
    "cero",
    "commix",
    "crlfuzz",
    "dalfox",
    "dnsgen",
    "dnsrecon",
    "dnsvalidator",
    "dnsx",
    "exec",
    "ffuf",
    "ffuf_base",
    "ffuz",
    "gau",
    "github-endpoints",
    "github-subdomains",
    "gorgo",
    "gowitness",
    "gxss",
    "http2smugl",
    "httpx",
    "ipcdn",
    "katana",
    "linkfinder",
    "masscan",
    "massdns",
    "naabu",
    "naabu-nmap",
    "nmap",
    "nmapx",
    "nuclei",
    "nuclei-screenshots",
    "openredirex",
    "paramspider",
    "puredns-bruteforce",
    "puredns-resolve",
    "puredns-single",
    "s3scanner",
    "scrying",
    "sqlmap",
    "subjs",
    "testssl",
    "tlsx",
    "trufflehog",
    "unimap",
    "whois",
  ],
  extras: [
    "amass",
    "anew",
    "aquatone",
    "arjun",
    "assetfinder",
    "aws-cli",
    "cero",
    "chaos-client",
    "cloud_enum",
    "commix",
    "crlfuzz",
    "dalfox",
    "dirsearch",
    "dnsx",
    "dnsvalidator",
    "droopescan",
    "feroxbuster",
    "ffuf",
    "gau",
    "gauplus",
    "gobuster",
    "gospider",
    "gowitness",
    "gxss",
    "hakrawler",
    "hakrevdns",
    "httprobe",
    "httpx",
    "interactsh-client",
    "ipcdn",
    "jaeles",
    "katana",
    "kiterunner",
    "kxss",
    "linkfinder",
    "masscan",
    "massdns",
    "meg",
    "naabu",
    "nmap",
    "nuclei",
    "puredns",
    "rustscan",
    "s3scanner",
    "scrying",
    "secretfinder",
    "shuffledns",
    "sqlmap",
    "subfinder",
    "subjs",
    "testssl",
    "tlsx",
    "trufflehog",
    "unimap",
    "wafw00f",
    "waybackurls",
    "webscreenshot",
    "whois",
    "wpscan",
  ],
};

export const PROVISIONER_LABELS: Record<string, string> = {
  barebones: "Barebones",
  default: "Default",
  reconftw: "ReconFTW",
  extras: "Extras",
};

/** Returns true if module is likely available for the given provisioner image. */
export function isModuleAvailable(
  moduleName: string,
  provisioner: string,
): boolean {
  if (!provisioner || provisioner === "unknown") return true;
  const tools = PROVISIONER_TOOLS[provisioner.toLowerCase()] ?? [];
  if (!tools.length) return true;
  const mod = moduleName.toLowerCase();
  return tools.some((tool) => mod.includes(tool) || tool.includes(mod));
}

/** Finds which provisioner images include this module (for tooltip text). */
export function getRequiredProvisioners(moduleName: string): string[] {
  return Object.entries(PROVISIONER_TOOLS)
    .filter(([, tools]) => {
      const mod = moduleName.toLowerCase();
      return tools.some((t) => mod.includes(t) || t.includes(mod));
    })
    .map(([key]) => PROVISIONER_LABELS[key] ?? key);
}
