#!/usr/bin/env bash
# Wraps the real `aws` CLI so `aws ec2 describe-regions` transparently drops
# excluded regions from its output.
#
# axiom's own scripts (providers/aws-functions.sh, interact/account-helpers/aws.sh)
# call `aws ec2 describe-regions --query "Regions[].RegionName"` directly and
# loop over every result with `--region "$r"`. If one of those regions is
# having an outage, every axiom command that touches "all regions" (security
# group sync, image lookups, fleet listing, etc.) hangs on it in turn. This
# wrapper stops those loops from ever reaching an excluded region — no AWS
# IAM permission needed (unlike `aws account disable-region`, which requires
# account:DisableRegion and isn't granted to axiom's scoped IAM user).
#
# Exclusions are read at RUNTIME from $AXIOM_EXCLUDED_REGIONS (space-separated
# region names), so you can change the list later via docker-compose.yml
# without re-running this script.
#
# Everything other than `ec2 describe-regions --query ...RegionName...` passes
# straight through to the real binary untouched — including axiom's own
# account/region-switching commands, which don't go through describe-regions.
#
# Usage (inside the container):
#   bash /app/tools/setup-aws-region-filter.sh
# Safe to re-run — detects an existing install and exits without changes.

set -euo pipefail

WRAPPER_PATH="/usr/local/bin/aws"
MARKER="# gui-ax-region-filter-wrapper"

if [[ -f "$WRAPPER_PATH" ]] && head -n3 "$WRAPPER_PATH" | grep -qF "$MARKER"; then
  echo "aws wrapper already installed at $WRAPPER_PATH — nothing to do."
  echo "Current exclusions come from \$AXIOM_EXCLUDED_REGIONS at call time: ${AXIOM_EXCLUDED_REGIONS:-<none set>}"
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required but not found in PATH." >&2
  exit 1
fi

# Find the real aws-cli v2 binary on disk — works whether /usr/local/bin/aws
# is currently the original symlink or (on a re-run after a failed install)
# already our wrapper. Prefer the installer's `current` symlink: when multiple
# versions are installed side by side (e.g. after a downgrade), a bare `find`
# could otherwise pick the wrong/older/newer dist/aws.
if [[ -x /usr/local/aws-cli/v2/current/dist/aws ]]; then
  REAL_AWS="$(readlink -f /usr/local/aws-cli/v2/current/dist/aws)"
else
  REAL_AWS="$(find /usr/local/aws-cli -type f -name aws -path '*/dist/aws' 2>/dev/null | head -n1)"
fi
if [[ -z "$REAL_AWS" ]]; then
  echo "Could not locate the real aws-cli v2 binary under /usr/local/aws-cli — is AWS CLI v2 installed?" >&2
  exit 1
fi

# The AWS CLI v2 installer makes /usr/local/bin/aws a SYMLINK into
# .../current/dist/aws. Writing with `cat >` would follow that symlink and
# overwrite the real binary. Remove the path first so we always create a fresh
# regular file and never clobber the actual CLI.
rm -f "$WRAPPER_PATH"

cat > "$WRAPPER_PATH" <<WRAPPER_EOF
#!/usr/bin/env bash
$MARKER — real binary: $REAL_AWS
# Auto-generated by tools/setup-aws-region-filter.sh — passes every command
# straight through to the real aws CLI, except \`ec2 describe-regions\`
# queries for RegionName, whose result is filtered against
# \$AXIOM_EXCLUDED_REGIONS (space-separated region names, e.g. "me-south-1").
REAL_AWS="$REAL_AWS"

if [[ "\${1:-}" == "ec2" && "\${2:-}" == "describe-regions" ]] \\
   && printf '%s\\n' "\$@" | grep -q 'RegionName'; then
  exclude="\${AXIOM_EXCLUDED_REGIONS:-}"
  all_json="\$("\$REAL_AWS" ec2 describe-regions --output json)" || exit \$?
  if [[ -z "\$exclude" ]]; then
    filtered_json="\$all_json"
  else
    filtered_json="\$(echo "\$all_json" | jq --arg excl "\$exclude" '
      (\$excl | split(" ")) as \$ex
      | .Regions |= map(select(.RegionName as \$r | (\$ex | index(\$r)) | not))
    ')"
  fi
  if printf ' %s' "\$@" | grep -q -- ' --output text'; then
    # AWS's own '--output text' for a flat list is tab-separated on one line.
    echo "\$filtered_json" | jq -r '.Regions[].RegionName' | paste -sd'\\t'
  else
    # Default/json output: axiom does '--query "Regions[*].RegionName" | jq -r .[]'
    # so it expects a JSON array here.
    echo "\$filtered_json" | jq -c '[.Regions[].RegionName]'
  fi
else
  exec "\$REAL_AWS" "\$@"
fi
WRAPPER_EOF
chmod +x "$WRAPPER_PATH"

echo "✓ aws wrapper installed at $WRAPPER_PATH (real binary preserved at $REAL_AWS)"
echo "  Set AXIOM_EXCLUDED_REGIONS (space-separated) in docker-compose.yml to control what's filtered."
echo "  Currently: ${AXIOM_EXCLUDED_REGIONS:-<none set — filtering is a no-op until you set it>}"
