#!/usr/bin/env bash
# Wraps the real `aws` CLI so commands that involve excluded regions never
# reach AWS — they're intercepted locally and return empty/filtered results.
#
# Two interception rules (both keyed on $AXIOM_EXCLUDED_REGIONS):
#
#   1. `aws ec2 describe-regions` — strips excluded regions from the output.
#      axiom iterates every region returned by this call and issues a
#      describe-instances for each one.  Filtering here stops those loops from
#      ever reaching a blocked region.
#
#   2. `aws ec2 describe-instances --region <excluded>` — returns an empty
#      {"Reservations":[]} immediately without contacting AWS.  Belt-and-
#      suspenders for any code path (axiom-rm, axiom-scp status polling, the
#      create_instances wait loop) that passes a hardcoded region without first
#      going through describe-regions.
#
# Exclusions are read at RUNTIME from $AXIOM_EXCLUDED_REGIONS (space-separated
# region names), so you can change the list later via docker-compose.yml
# without re-running this script.
#
# The real aws binary is exec'd for everything else — no performance impact on
# normal calls.
#
# Usage (inside the container):
#   bash /app/tools/setup-aws-region-filter.sh          # install / upgrade
#   bash /app/tools/setup-aws-region-filter.sh --force  # reinstall even if already present
#
# Long-term AWS-side fix: disable the regions at account level from the AWS
# console (Account → Regions → Disable).  Once disabled, aws ec2
# describe-regions won't return them natively, making this wrapper redundant.
# The axiom-runner IAM user lacks account:DisableRegion, so that must be done
# from the root/admin account.

set -euo pipefail

WRAPPER_PATH="/usr/local/bin/aws"
MARKER="# gui-ax-region-filter-wrapper-v2"

if [[ "${1:-}" != "--force" ]] \
   && [[ -f "$WRAPPER_PATH" ]] \
   && head -n3 "$WRAPPER_PATH" | grep -qF "$MARKER"; then
  echo "aws wrapper (v2) already installed at $WRAPPER_PATH — nothing to do."
  echo "  Run with --force to reinstall."
  echo "  Current exclusions from \$AXIOM_EXCLUDED_REGIONS: ${AXIOM_EXCLUDED_REGIONS:-<none set>}"
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required but not found in PATH." >&2
  exit 1
fi

# Find the real aws-cli v2 binary on disk — works whether /usr/local/bin/aws
# is currently the original symlink or (on a re-run) already our wrapper.
if [[ -x /usr/local/aws-cli/v2/current/dist/aws ]]; then
  REAL_AWS="$(readlink -f /usr/local/aws-cli/v2/current/dist/aws)"
else
  REAL_AWS="$(find /usr/local/aws-cli -type f -name aws -path '*/dist/aws' 2>/dev/null | head -n1)"
fi
if [[ -z "$REAL_AWS" ]]; then
  echo "Could not locate the real aws-cli v2 binary under /usr/local/aws-cli — is AWS CLI v2 installed?" >&2
  exit 1
fi

# Remove existing file (may be a symlink into the real binary — never clobber it).
rm -f "$WRAPPER_PATH"

cat > "$WRAPPER_PATH" <<WRAPPER_EOF
#!/usr/bin/env bash
$MARKER — real binary: $REAL_AWS
# Auto-generated by tools/setup-aws-region-filter.sh
# Intercepts excluded-region AWS calls so they never reach IAM deny policies.
REAL_AWS="$REAL_AWS"

_excl="\${AXIOM_EXCLUDED_REGIONS:-}"

# ── Rule 1: describe-regions ──────────────────────────────────────────────────
# Strip excluded regions from the region list axiom loops over.
if [[ "\${1:-}" == "ec2" && "\${2:-}" == "describe-regions" ]] \\
   && printf '%s\\n' "\$@" | grep -q 'RegionName'; then
  all_json="\$("\$REAL_AWS" ec2 describe-regions --output json)" || exit \$?
  if [[ -z "\$_excl" ]]; then
    filtered_json="\$all_json"
  else
    filtered_json="\$(echo "\$all_json" | jq --arg excl "\$_excl" '
      (\$excl | split(" ")) as \$ex
      | .Regions |= map(select(.RegionName as \$r | (\$ex | index(\$r)) | not))
    ')"
  fi
  if printf ' %s' "\$@" | grep -q -- ' --output text'; then
    echo "\$filtered_json" | jq -r '.Regions[].RegionName' | paste -sd'\\t'
  else
    echo "\$filtered_json" | jq -c '[.Regions[].RegionName]'
  fi
  exit 0
fi

# ── Rule 2: describe-instances for an excluded region ─────────────────────────
# Return empty Reservations instead of hitting an IAM explicit-deny.
# Covers: axiom-rm, axiom-scp status polling, create_instances wait loop.
if [[ "\${1:-}" == "ec2" && "\${2:-}" == "describe-instances" && -n "\$_excl" ]]; then
  _req_region=""
  _args=("\$@")
  for _i in "\${!_args[@]}"; do
    if [[ "\${_args[\$_i]}" == "--region" ]]; then
      _req_region="\${_args[\$((_i+1))]:-}"
      break
    fi
  done
  if [[ -n "\$_req_region" ]]; then
    for _ex in \$_excl; do
      if [[ "\$_req_region" == "\$_ex" ]]; then
        echo '{"Reservations":[]}'
        exit 0
      fi
    done
  fi
fi

# ── Passthrough ───────────────────────────────────────────────────────────────
exec "\$REAL_AWS" "\$@"
WRAPPER_EOF
chmod +x "$WRAPPER_PATH"

echo "✓ aws wrapper (v2) installed at $WRAPPER_PATH (real binary: $REAL_AWS)"
echo "  Excluded regions (from \$AXIOM_EXCLUDED_REGIONS): ${AXIOM_EXCLUDED_REGIONS:-<none set — filtering is a no-op>}"
